### ISSUE TITLE
[Feat] 단어 추가 뷰 레이아웃

### ISSUE THREAD

**Issue by 2youngjun** [2youngjun/Nadam#1]
### TODO
- [ ] 완료 / 취소 버튼
- [ ] 단어 / 뜻 TextField 및 Border 설정
- [ ] 하프 모달 뷰
- [ ] 각 컴포넌트 별 정확한 Auto Layout 구현
