### ISSUE TITLE
[Feat] 단어 테스트 를 통한 포인트 적립 및 이를 활용하여 펫을 꾸미는 PetView & PurchasingView 구현합니다.

### ISSUE THREAD

**Issue by 2youngjun** [2youngjun/Nadam#25]
### TODO
- [x] PetView 레이아웃 구현
- [x] PurchasingView 레이아웃 구현
- [x] PetView 기능 구현
- [x] PurchasingView 기능 구현
- [x] TestView 종료 시 Toast Alarm 구현
- [x] PetView, PurchasingView Asset 추가
