### ISSUE TITLE
[Fix] 출시 후 피드백 받은 버그들을 수정합니다.

### ISSUE THREAD

**Issue by 2youngjun** [2youngjun/Nadam#29]
## Description
- MatchView 에서의 수정 사항을 반영하고, 음악 매칭 이슈를 해결합니다.

## Tasks
- [x] PetView 에서의 백그라운드 이미지에 대한 기기별 대응이 필요합니다.
- [x] 단어만 입력하고, 단어 뜻을 입력하지 않아도 저장 버튼이 활성화 되는 이슈를 해결합니다.
- [x] WordListView(메인 뷰) 에서 단어 뜻이 길어질 경우 단어 공간을 침범하는 이슈를 해결합니다.
- [x] 단어 추가/수정 모드에서 SaveButton의 상태에 대한 TextField 로직을 수정합니다.
