### ISSUE TITLE
[Refactor] Papago API Networking 코드 모듈화 및 두 번째 게임을 단어 뜻 게임으로 수정

### ISSUE THREAD

**Issue by 2youngjun** [2youngjun/Nadam#31]
### TODO
- [x] Papago API Networking 코드 분리
- [x] 기존 단어 철자 맞추는 두 번째 게임을 단어 의미 맞추는 게임으로 변경
- [x] 디렉터리 수정 및 일부 파일명 변경
